name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Iamge
      uses: docker/build-push-action@v1
      with: 
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        repository: username/repository
        tag_with_sha: true
        path: ''

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag libaibai/gohellobuild
    - name: Push the Docker image
      run: docker push . --tag libaibai/gohellobuild
